@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.cookingforblockheads.block.fridge;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;